"""Benchmarks are generated, never asserted. This reads the journals, the suite
result log, and the register (surface) logs and emits BENCHMARKS.md with only
measured numbers and their regeneration commands.

Instruments: outcomes, wall clock, tokens per dispatch AND per landed outcome,
tokens by role, outcome rates with host-outage stalls separated from machine
failures."""

import json
import statistics
from pathlib import Path

from . import paths
from .journal import Journal, run_ids
from .util import read_jsonl

HOST_OUTCOMES = {"outage", "stalled", "killed"}  # host/engine death, not the worker's fault
MACHINE_FAIL = {"failed", "timeout"}


def collect() -> dict:
    dispatches, phases, runs, surfaces, reviews = [], [], [], [], []
    for rid in run_ids():
        st = Journal(rid).state()
        rows = Journal(rid).rows()
        runs.append({"run": rid, "closed": st["closed"], "stopped": st["stopped"],
                     "wall_s": (st.get("closed_at") or 0) - (st.get("opened_at") or 0) if st.get("closed_at") and st.get("opened_at") else None,
                     "tokens": st["tokens_total"], "cost": st["cost_total"], "relights": st["relights"],
                     "recoveries": sum(st["recoveries"].values())})
        for d in st["dispatches"].values():
            if d.get("outcome") is not None:
                dispatches.append({"run": rid, **d})
        for k, p in st["phases"].items():
            phases.append({"run": rid, "phase": k, **p})
        for r in rows:
            if r["event"] == "surface.score":
                surfaces.append(r)
            elif r["event"] == "review.verdict":
                reviews.append(r)
    suite = read_jsonl(paths.state_dir() / "suite.jsonl")
    return {"runs": runs, "dispatches": dispatches, "phases": phases, "surfaces": surfaces, "reviews": reviews, "suite": suite}


def _pct(n, d):
    return f"{(100.0 * n / d):.1f}%" if d else "n/a"


def _med(xs):
    xs = [x for x in xs if x is not None]
    return f"{statistics.median(xs):.1f}" if xs else "n/a"


def _sum_tok(ds):
    return sum(((d.get("tokens") or {}).get("total") or 0) for d in ds)


def render(data: dict) -> str:
    D, R, P = data["dispatches"], data["runs"], data["phases"]
    out = ["# BENCHMARKS", "",
           "Generated by `pipeline bench` from the journal, the suite log, and the surface logs.",
           "Every number below is measured; none is asserted. Regenerate: `pipeline bench > BENCHMARKS.md`.", ""]
    out += ["## Runs", "", f"- runs recorded: {len(R)}",
            f"- done: {sum(1 for r in R if r['closed'] == 'done')}; stopped: {sum(1 for r in R if r['closed'] == 'stopped')}; open: {sum(1 for r in R if r['closed'] is None)}",
            f"- median run wall clock (closed runs): {_med([r['wall_s'] for r in R if r['wall_s']])} s",
            f"- relights by sentry: {sum(r['relights'] for r in R)}; stall recoveries: {sum(r['recoveries'] for r in R)}", ""]
    ok = [d for d in D if d["outcome"] == "ok"]
    host = [d for d in D if d["outcome"] in HOST_OUTCOMES]
    mach = [d for d in D if d["outcome"] in MACHINE_FAIL]
    out += ["## Dispatch outcomes", "", f"- dispatches: {len(D)}",
            f"- ok: {len(ok)} ({_pct(len(ok), len(D))})",
            f"- machine failures (failed/timeout): {len(mach)} ({_pct(len(mach), len(D))})",
            f"- host-outage stalls (outage/stalled/killed), separated from machine failures: {len(host)} ({_pct(len(host), len(D))})",
            f"- ok rate excluding host stalls: {_pct(len(ok), len(D) - len(host))}", ""]
    out += ["## Wall clock", "", f"- median dispatch wall: {_med([d.get('wall_s') for d in D])} s",
            f"- p90 dispatch wall: {_p90([d.get('wall_s') for d in D])} s", ""]
    landed = [p for p in P if p.get("status") == "done"]
    out += ["## Tokens", "", f"- total tokens: {_sum_tok(D)}",
            f"- tokens per dispatch (median): {_med([((d.get('tokens') or {}).get('total')) for d in D])}",
            f"- tokens per landed outcome (total tokens / done phases): {(_sum_tok(D) / len(landed)):.0f}" if landed else "- tokens per landed outcome: n/a (no landed phases)",
            f"- cost total: {sum(d.get('cost') or 0 for d in D):.4f}", "", "### Tokens by role", "", "| role | dispatches | tokens | ok rate |", "|---|---|---|---|"]
    by_role = {}
    for d in D:
        by_role.setdefault(d.get("role"), []).append(d)
    for role, ds in sorted(by_role.items(), key=lambda kv: str(kv[0])):
        out.append(f"| {role} | {len(ds)} | {_sum_tok(ds)} | {_pct(sum(1 for d in ds if d['outcome'] == 'ok'), len(ds))} |")
    out.append("")
    out += ["### Tokens by model", "", "| model | dispatches | tokens | ok rate |", "|---|---|---|---|"]
    by_model = {}
    for d in D:
        by_model.setdefault(d.get("model"), []).append(d)
    for m, ds in sorted(by_model.items(), key=lambda kv: str(kv[0])):
        out.append(f"| {m} | {len(ds)} | {_sum_tok(ds)} | {_pct(sum(1 for d in ds if d['outcome'] == 'ok'), len(ds))} |")
    out.append("")
    att = [p.get("attempts") or 0 for p in landed]
    out += ["## Phases", "", f"- phases seen: {len(P)}; done: {len(landed)}; failed/burned: {sum(1 for p in P if p.get('status') == 'failed')}",
            f"- first-attempt landing rate: {_pct(sum(1 for a in att if a == 1), len(att))}", ""]
    S = data["surfaces"]
    out += ["## Surface register", "", f"- scorings: {len(S)}; pass: {sum(1 for s in S if s.get('pass'))} ({_pct(sum(1 for s in S if s.get('pass')), len(S))})",
            f"- rewrite passes: {sum(1 for s in S if s.get('rewrite') and s.get('pass'))} of {sum(1 for s in S if s.get('rewrite'))} rewrites", ""]
    V = data["reviews"]
    out += ["## Cross review", "", f"- verdicts: {len(V)}"]
    for v in ("PASS", "CONCERNS", "BLOCKING", "UNAVAILABLE"):
        out.append(f"- {v}: {sum(1 for r in V if r.get('verdict') == v)}")
    out.append("")
    T = data["suite"]
    if T:
        last = T[-1]
        out += ["## Characterization suite (last run)", "", f"- when: {last.get('ts')}", f"- tests: {last.get('total')} passed: {last.get('passed')} failed: {last.get('failed')}",
                f"- wall: {last.get('wall_s')} s", f"- ratchet: {last.get('total')} tests vs ledger floor {last.get('floor')}",
                "- regenerate: `pipeline suite`", ""]
    else:
        out += ["## Characterization suite", "", "- no suite runs logged yet (`pipeline suite`)", ""]
    out += ["## Regeneration", "", "```", "pipeline suite      # appends to <estate>/state/suite.jsonl", "pipeline bench > BENCHMARKS.md", "```", ""]
    return "\n".join(out)


def _p90(xs):
    xs = sorted(x for x in xs if x is not None)
    if not xs:
        return "n/a"
    return f"{xs[min(len(xs) - 1, int(0.9 * len(xs)))]:.1f}"
